/* Route C fibre worker: configuration VII, fibre over lambda = n/d.

   The fibre is v^2 = c33(p, q) (see route_c_cells.gp, generated by route_c_model.py).
   With t = q/p and the base point (1:0), the Connell transformation gives the
   Weierstrass curve E; rc_t() maps a point of E back to t.

   rc_fibre(n, d, hmax) returns
       [status, [r, R], ngens, ntors, npts, nbad, hits]
   status   "ok" (rank proven, rank-many generators, saturated at primes <= 50),
            ntors = size of the torsion subgroup;
            "rank-unproven" or "gens-incomplete" (searched with the points found),
            "singular" or "error ..."
   npts     points of E with canonical height <= hmax (PARI normalization),
            counting P and -P separately, plus torsion translates
   nbad     points whose image failed the c33-is-square sanity check (must be 0)
   hits     [n, d, p, q, nsq, flags, grid] for every non-trivial grid with
            >= 7 square cells; flags = [c11, c12, c32] square or not.          */

read("route_c_cells.gp");

RC_SEEDB = 300;     \\ height bound for the ratpoints seed search on the quartic
RC_EFFMAX = 3;      \\ largest ellrank effort tried on the fibre itself
RC_ISOEFF = 3;      \\ ellrank effort on the 2-isogenous curves when generators are missing
RC_TLIM = 120;      \\ seconds allowed per fibre (rc_line); over that the fibre is "timeout"

rc_curve(n, d) =
{
  my(co = rc_quartic(n, d), q0 = rc_q0(n, d));
  my(D = co[2], C = co[3], B = co[4], A = co[5]);
  if(co[1] != q0^2, error("constant term is not q0^2"));
  my(a2 = C - D^2/(4*q0^2), a4 = -4*q0^2*A);
  [[D/q0, a2, 2*q0*B, a4, a2*a4], [q0, A, B, C, D]];
}

/* point of the original Connell model -> t = q/p (oo for p = 0) */
rc_t(P, cf) =
{
  my(q0 = cf[1], C = cf[4], D = cf[5]);
  if(#P < 2, return(0));                       \\ point at infinity -> base point t = 0
  if(P[2] == 0, return(oo));
  (2*q0*(P[1] + C) - D^2/(2*q0)) / P[2];
}

rc_issq(x) = x >= 0 && issquare(x);

/* small points of the fibre, mapped to the minimal model: seeds for ellrank.
   Bremner's two sections R, S of the fibration lie at t = +-1 and t = (n+d)/(n-d),
   -(n-d)/(n+d); ratpoints also finds them, plus any other small points. */
rc_seeds(n, d, cv, Em, ch, B) =
{
  my(cf = cv[2], q0 = cf[1], A = cf[2], Bc = cf[3], C = cf[4], D = cf[5], P, L = List(), x = 'x);
  my(f = A*x^4 + Bc*x^3 + C*x^2 + D*x + q0^2);
  my(R = iferr(hyperellratpoints(f, B), e, []));
  foreach(R, pt,
    my(t = pt[1], v = pt[2]);
    if(t == 0, next);
    my(X = (2*q0*(v + q0) + D*t)/t^2, Y = (4*q0^2*(v + q0) + 2*q0*(D*t + C*t^2) - D^2*t^2/(2*q0))/t^3);
    P = ellchangepoint([X, Y], ch);
    if(ellisoncurve(Em, P) && ellorder(Em, P) == 0, listput(L, P)));
  Vec(L);
}

/* grid at (p:q); returns 0 if trivial, else [nsq, flags, primitive grid] */
rc_grid(n, d, p, q) =
{
  my(g = rc_cells(n, d, p, q), G, sq, fl);
  if(!rc_issq(g[9]), return(-1));             \\ sanity: c33 must be a square
  if(#Set(g) < 9, return(0));                  \\ repeated entries: trivial
  G = content(g); g = g / (G / core(G));      \\ divide by the largest square dividing all cells
  sq = vector(9, i, rc_issq(g[i]));
  fl = [sq[1], sq[2], sq[8]];
  [vecsum(sq), fl, g];
}

/* every torsion point of E (not just the generators) */
rc_torsion(E) =
{
  my(T = elltors(E), L = List());
  if(#T[3] == 0, return([[0]]));
  if(#T[3] == 1,
    for(a = 0, T[2][1] - 1, listput(L, ellmul(E, T[3][1], a))),
    for(a = 0, T[2][1] - 1, for(b = 0, T[2][2] - 1,
      listput(L, elladd(E, ellmul(E, T[3][1], a), ellmul(E, T[3][2], b))))));
  Vec(L);
}

rc_indep(E, G) = #G == 0 || abs(matdet(ellheightmatrix(E, G))) > 1e-20;

/* rank proven but points missing: search the 2-isogenous curves (smaller heights) and map
   their points back through the dual isogeny.  Adapted from perfect-cuboid-tools
   route_d_isogpoints.gp (isogpts).  Needs full 2-torsion. */
rc_isogpts(Em, G, rk, eff) =
{
  my(T2 = select(P -> P != [0] && ellorder(Em, P) == 2, rc_torsion(Em)));
  if(#T2 < 2, return(G));
  for(i = 1, #T2,
    my(I = ellisogeny(Em, T2[i]), E2 = ellinit(I[1]), r2 = ellrank(E2, eff), j = if(i == 1, 2, 1));
    my(K2 = ellisogenyapply(I[2], T2[j]), J = ellisogeny(E2, K2), E3 = ellinit(J[1]), v3, m3 = ellminimalmodel(E3, &v3));
    if(m3[1..5] != Em[1..5], error("rc_isogpts: dual isogeny does not return to Em"));
    foreach(r2[4], Q,
      my(R = ellchangepoint(ellisogenyapply(J[2], Q), v3));
      if(!ellisoncurve(Em, R), error("rc_isogpts: mapped point not on Em"));
      if(R != [0] && rc_indep(Em, concat(G, [R])), G = concat(G, [R])));
    if(#G >= rk, break));
  G;
}

/* curve, rank bounds and generators of the fibre: [cv, Em, ch, [r, R], G] or an error string */
rc_setup(n, d) =
{
  my(cv, E, Em, ch, rk, eff, G);
  if(gcd(n, d) != 1 || d <= 0, return("error bad lambda"));
  cv = rc_curve(n, d);
  E = iferr(ellinit(cv[1]), err, 0);
  if(E == 0 || #E == 0, return("singular"));
  Em = ellminimalmodel(E, &ch);
  \\ seed with small points, then raise the effort (at most to RC_EFFMAX) until the rank is
  \\ proven and we hold rank-many independent points; known points are always passed back in
  my(S = rc_seeds(n, d, cv, Em, ch, RC_SEEDB));
  eff = 0; rk = ellrank(Em, eff, S);
  while((rk[1] != rk[2] || #rk[4] < rk[1]) && eff < RC_EFFMAX, eff++; rk = ellrank(Em, eff, rk[4]));
  G = rk[4];
  if(rk[1] == rk[2] && #G < rk[1], G = rc_isogpts(Em, G, rk[1], RC_ISOEFF));
  [cv, Em, ch, [rk[1], rk[2]], G];
}

rc_fibre(n, d, hmax) =
{
  my(s = rc_setup(n, d));
  if(type(s) == "t_STR", return([s, [0, 0], 0, 0, 0, 0, []]));
  rc_search(n, d, hmax, s[1], s[2], s[3], s[4], s[5]);
}

/* saturate G and test every point of height <= hmax (plus torsion translates) */
rc_search(n, d, hmax, cv, Em, ch, rk, G) =
{
  my(T, H, V, pts, nb = 0, hits = List(), np = 0, t, p, q, r);
  if(#G, G = ellsaturation(Em, G, 50));
  T = rc_torsion(Em);
  pts = List();
  if(#G,
    H = ellheightmatrix(Em, G);
    V = qfminim(H, hmax, , 2)[3];
    for(j = 1, #V,
      my(P = [0]);
      for(i = 1, #G, if(V[i, j], P = elladd(Em, P, ellmul(Em, G[i], V[i, j]))));
      listput(pts, P); listput(pts, ellneg(Em, P))));
  listput(pts, [0]);
  for(k = 1, #pts,
    for(j = 1, #T,
      my(P = elladd(Em, pts[k], T[j]), P0 = ellchangepointinv(P, ch));
      t = rc_t(P0, cv[2]);
      if(t === oo, p = 0; q = 1, p = denominator(t); q = numerator(t));
      if(p == 0 && q == 0, next);
      np++;
      r = rc_grid(n, d, p, q);
      if(r === -1, nb++; next);
      if(r === 0, next);
      if(r[1] >= 7, listput(hits, [n, d, p, q, r[1], r[2], r[3]]))));
  [if(rk[1] != rk[2], "rank-unproven", #G < rk[1], "gens-incomplete", "ok"), [rk[1], rk[2]], #G, #T, np, nb, Vec(hits)];
}

/* stage 3 export: one JSON line with the minimal model, rank bounds and known generators,
   read by route_c_mwrank.sage.  Rationals are written as strings "p/q". */
rc_qstr(x) = Str("\"", x, "\"");
rc_export(n, d) =
{
  my(s = iferr(rc_setup(n, d), err, Str("error ", errname(err))));
  if(type(s) == "t_STR",
    print("EXP {\"n\":", n, ",\"d\":", d, ",\"error\":\"", s, "\"}"); return);
  my(a = s[2][1..5], G = s[5]);
  print("EXP {\"n\":", n, ",\"d\":", d,
        ",\"a\":[", strjoin(apply(rc_qstr, a), ","), "]",
        ",\"rk\":[", s[4][1], ",", s[4][2], "]",
        ",\"gens\":[", strjoin(apply(P -> Str("[", rc_qstr(P[1]), ",", rc_qstr(P[2]), "]"), G), ","), "]}");
}

/* stage 3 re-search with extra generators Gx (points on the same minimal model, e.g. from
   mwrank) and external rank bounds rkx = [r, R]; every external point is checked. */
rc_fibre_with(n, d, hmax, Gx, rkx) =
{
  my(s = rc_setup(n, d));
  if(type(s) == "t_STR", return([s, [0, 0], 0, 0, 0, 0, []]));
  my(Em = s[2], G = s[5], lo, hi);
  foreach(Gx, P,
    if(!ellisoncurve(Em, P), error("rc_fibre_with: external point not on Em"));
    if(ellorder(Em, P) == 0 && rc_indep(Em, concat(G, [P])), G = concat(G, [P])));
  lo = vecmax([s[4][1], rkx[1], #G]);
  hi = vecmin([s[4][2], rkx[2]]);
  if(lo > hi, error("rc_fibre_with: rank bounds inconsistent"));
  rc_search(n, d, hmax, s[1], Em, s[3], [lo, hi], G);
}

rc_line_with(n, d, hmax, Gx, rkx) =
{
  my(r = iferr(alarm(RC_TLIM, rc_fibre_with(n, d, hmax, Gx, rkx)), err,
               [Str("error ", errname(err)), [0, 0], 0, 0, 0, 0, []]));
  if(type(r) == "t_ERROR", r = [if(errname(r) == "e_ALARM", "timeout", Str("error ", errname(r))), [0, 0], 0, 0, 0, 0, []]);
  print("FIB ", n, " ", d, " | ", r[1], " | ", r[2], " | ", r[3], " | ", r[4], " | ", r[5], " | ", r[6], " | ", r[7]);
}

/* one output line per lambda, parsed by route_c_run.py */
rc_line(n, d, hmax) =
{
  \\ alarm() returns (does not raise) the e_ALARM error object when time runs out
  my(r = iferr(alarm(RC_TLIM, rc_fibre(n, d, hmax)), err,
               [Str("error ", errname(err)), [0, 0], 0, 0, 0, 0, []]));
  if(type(r) == "t_ERROR", r = [if(errname(r) == "e_ALARM", "timeout", Str("error ", errname(r))), [0, 0], 0, 0, 0, 0, []]);
  print("FIB ", n, " ", d, " | ", r[1], " | ", r[2], " | ", r[3], " | ", r[4], " | ", r[5], " | ", r[6], " | ", r[7]);
}
